#pragma once

#include "PhysXLoader.h"

enum E_COLLISION_FLAG
{
	COLLISION_FLAG_GROUND				= 1 << 0,
	COLLISION_FLAG_WHEEL				= 1 << 1,
	COLLISION_FLAG_CHASSIS				= 1 << 1,
	COLLISION_FLAG_OBSTACLE				= 1 << 1,
	COLLISION_FLAG_DRIVABLE_OBSTACLE	= 1 << 1,

	COLLISION_FLAG_GROUND_AGAINST		= COLLISION_FLAG_CHASSIS | COLLISION_FLAG_OBSTACLE | COLLISION_FLAG_DRIVABLE_OBSTACLE,
	COLLISION_FLAG_WHEEL_AGAINST		= COLLISION_FLAG_WHEEL | COLLISION_FLAG_CHASSIS | COLLISION_FLAG_OBSTACLE,
	COLLISION_FLAG_CHASSIS_AGAINST		= COLLISION_FLAG_GROUND | COLLISION_FLAG_WHEEL | COLLISION_FLAG_CHASSIS | COLLISION_FLAG_OBSTACLE | COLLISION_FLAG_DRIVABLE_OBSTACLE,
	COLLISION_FLAG_OBSTACLE_AGAINST		= COLLISION_FLAG_GROUND | COLLISION_FLAG_WHEEL | COLLISION_FLAG_CHASSIS | COLLISION_FLAG_OBSTACLE | COLLISION_FLAG_DRIVABLE_OBSTACLE,
	COLLISION_FLAG_DRIVABLE_OBSTACLE_AGAINST = COLLISION_FLAG_GROUND | COLLISION_FLAG_CHASSIS | COLLISION_FLAG_OBSTACLE | COLLISION_FLAG_DRIVABLE_OBSTACLE
};

PxFilterFlags VehicleFilterShader(
	PxFilterObjectAttributes Attr0, PxFilterData FilterData0,
	PxFilterObjectAttributes Attr1, PxFilterData FilterData1,
	PxPairFlags &PairFlags, void const *pConstantBlock, PxU32 dwConstantBlockSize);